-- V1: esquema base completo.
--
-- Generado desde las entidades JPA reales (Hibernate SchemaExport, sin tocar
-- ninguna base de datos: solo lee los @Entity y escribe el DDL), no escrito
-- a mano. Si necesitas regenerarlo o revisar como se hizo, ver el commit que
-- introduce este archivo.
--
-- De aqui en adelante, cualquier cambio de esquema (columna nueva, tabla
-- nueva, etc.) es una migracion nueva: V2__algo.sql, V3__otra_cosa.sql, etc.
-- Nunca se edita un archivo V* ya aplicado.

CREATE SCHEMA IF NOT EXISTS seguridad;
CREATE SCHEMA IF NOT EXISTS catalogo;
CREATE SCHEMA IF NOT EXISTS ventas;
CREATE SCHEMA IF NOT EXISTS gestion_agencias;


    create table catalogo.destino (
        activo boolean not null default true not null,
        fecha_creacion timestamp not null default now() not null,
        id_destino bigint generated by default as identity,
        nombre varchar(100) not null,
        pais varchar(100) not null,
        descripcion text,
        primary key (id_destino)
    );

    create table catalogo.paquete (
        destacado boolean not null,
        fecha_cierre_venta date,
        fecha_fin_viaje date,
        fecha_inicio_viaje date,
        moneda varchar(3),
        precio_desde numeric(10,2),
        fecha_actualizacion timestamp(6) not null,
        fecha_creacion timestamp(6) not null,
        id_destino bigint not null,
        id_paquete bigint generated by default as identity,
        estado varchar(20) not null,
        categoria varchar(50),
        duracion_texto varchar(50),
        nombre varchar(100) not null unique,
        descripcion text,
        primary key (id_paquete)
    );

    create table catalogo.paquete_aliado (
        id_paquete bigint not null,
        aerolinea varchar(100),
        unique (id_paquete, aerolinea)
    );

    create table catalogo.paquete_opcion (
        fecha_desde date not null,
        fecha_hasta date not null,
        orden integer not null,
        precio_doble numeric(10,2) not null,
        precio_nino numeric(10,2) not null,
        precio_simple numeric(10,2) not null,
        precio_triple numeric(10,2) not null,
        id_paquete bigint not null,
        id_paquete_opcion bigint generated by default as identity,
        incluye varchar(50),
        hotel_servicio varchar(150) not null,
        primary key (id_paquete_opcion)
    );

    create table catalogo.paquete_vuelo (
        orden integer not null,
        fecha_llegada timestamp(6) not null,
        fecha_salida timestamp(6) not null,
        id_paquete bigint not null,
        id_paquete_vuelo bigint generated by default as identity,
        aerolinea varchar(100) not null,
        destino varchar(100) not null,
        origen varchar(100) not null,
        primary key (id_paquete_vuelo)
    );

    create table catalogo.proveedor (
        activo boolean not null,
        fecha_actualizacion timestamp(6) not null,
        fecha_creacion timestamp(6) not null,
        id_destino bigint,
        id_proveedor bigint generated by default as identity,
        ruc varchar(11) not null unique,
        contacto_telefono varchar(20),
        condiciones_comerciales varchar(50),
        tipo_proveedor varchar(50),
        contacto_email varchar(100),
        contacto_nombre varchar(100),
        nombre_comercial varchar(200),
        razon_social varchar(200) not null,
        observaciones text,
        primary key (id_proveedor)
    );

    create table catalogo.servicio (
        activo boolean not null default true not null,
        fecha_creacion timestamp not null default now() not null,
        id_servicio bigint generated by default as identity,
        categoria varchar(50),
        nombre varchar(100) not null unique,
        descripcion text,
        primary key (id_servicio)
    );

    create table catalogo.tarifa (
        fecha_desde date not null,
        fecha_hasta date not null,
        moneda varchar(3) not null,
        precio numeric(10,2) not null,
        fecha_actualizacion timestamp(6) not null,
        fecha_creacion timestamp(6) not null,
        id_destino bigint not null,
        id_proveedor bigint not null,
        id_servicio bigint not null,
        id_tarifa bigint generated by default as identity,
        tipo_tarifa varchar(50),
        archivo_respaldo_url varchar(300),
        condiciones text,
        observaciones text,
        primary key (id_tarifa)
    );

    create table catalogo.tarifa_historial (
        precio_anterior numeric(10,2),
        precio_nuevo numeric(10,2) not null,
        fecha_cambio timestamp(6) not null,
        id_historial bigint generated by default as identity,
        id_tarifa bigint not null,
        id_usuario_cambio bigint,
        primary key (id_historial)
    );

    create table seguridad.historial_password (
        fecha_cambio timestamp(6) not null,
        id_historial bigint generated by default as identity,
        id_usuario bigint not null,
        hash_password varchar(100) not null,
        primary key (id_historial)
    );

    create table seguridad.password_reset_token (
        usado boolean not null,
        fecha_creacion timestamp(6) not null,
        fecha_expiracion timestamp(6) not null,
        id_token bigint generated by default as identity,
        id_usuario bigint not null,
        token varchar(64) not null unique,
        primary key (id_token)
    );

    create table seguridad.rol (
        activo boolean not null,
        es_sistema boolean not null,
        color varchar(7),
        fecha_actualizacion timestamp(6) not null,
        fecha_creacion timestamp(6) not null,
        id_rol bigint generated by default as identity,
        nombre varchar(60) not null unique,
        descripcion varchar(200),
        primary key (id_rol)
    );

    create table seguridad.rol_permiso (
        puede_actualizar boolean not null,
        puede_crear boolean not null,
        puede_eliminar boolean not null,
        puede_leer boolean not null,
        id_permiso bigint generated by default as identity,
        id_rol bigint not null,
        modulo varchar(60) not null,
        primary key (id_permiso)
    );

    create table seguridad.usuario (
        activo boolean not null,
        anonimizado boolean not null,
        fecha_creacion timestamp(6) not null,
        id_usuario bigint generated by default as identity,
        username varchar(50) not null unique,
        email varchar(100) not null unique,
        password_hash varchar(100) not null,
        primary key (id_usuario)
    );

    create table seguridad.usuario_rol (
        fecha_asignacion timestamp(6) not null,
        id_rol bigint not null,
        id_usuario bigint not null,
        id_usuario_rol bigint generated by default as identity,
        primary key (id_usuario_rol)
    );

    create table ventas.agencia (
        activo boolean not null,
        es_prioritaria boolean not null,
        fecha_creacion timestamp(6) not null,
        id_agencia bigint generated by default as identity,
        ruc varchar(11) not null unique,
        contacto_telefono varchar(20),
        categoria varchar(50),
        ciudad varchar(100),
        contacto_email varchar(100),
        contacto_nombre varchar(100),
        ejecutivo_asignado varchar(150),
        nombre_comercial varchar(200),
        razon_social varchar(200) not null,
        logo_url varchar(300),
        primary key (id_agencia)
    );

    create table ventas.cotizacion (
        fecha_viaje date,
        margen_porcentaje numeric(5,2) not null,
        fecha_cierre timestamp(6),
        fecha_creacion timestamp(6) not null,
        fecha_envio timestamp(6),
        id_agencia bigint not null,
        id_asesor bigint not null,
        id_cotizacion bigint generated by default as identity,
        numero varchar(20) not null unique,
        estado varchar(30) not null,
        servicios_adicionales text,
        primary key (id_cotizacion)
    );

    create table ventas.cotizacion_detalle (
        cantidad_pax integer not null,
        precio_unitario numeric(10,2) not null,
        id_cotizacion bigint not null,
        id_detalle bigint generated by default as identity,
        id_promocion bigint,
        id_tarifa bigint not null,
        primary key (id_detalle)
    );

    create table ventas.cotizacion_historial_estado (
        fecha_cambio timestamp(6) not null,
        id_cotizacion bigint not null,
        id_historial bigint generated by default as identity,
        id_usuario_cambio bigint not null,
        estado_anterior varchar(30),
        estado_nuevo varchar(30) not null,
        primary key (id_historial)
    );

    create table ventas.interaccion_agencia (
        fecha timestamp(6) not null,
        id_agencia bigint not null,
        id_interaccion bigint generated by default as identity,
        id_usuario_registro bigint,
        tipo varchar(50) not null,
        notas text,
        primary key (id_interaccion)
    );

    create table ventas.venta (
        comision numeric(12,2) not null,
        igv numeric(12,2) not null,
        monto_a_pagar numeric(12,2) not null,
        fecha_creacion timestamp(6) not null,
        fecha_culminada timestamp(6),
        fecha_venta timestamp(6) not null,
        id_agencia bigint not null,
        id_cotizacion bigint,
        id_detalle_pagos bigint,
        id_producto bigint,
        id_tarifa bigint,
        id_usuario_registro bigint,
        id_venta bigint generated by default as identity,
        numero varchar(20) not null unique,
        estado varchar(30) not null,
        notas_operativas text,
        primary key (id_venta)
    );

    create table ventas.venta_historial_estado (
        fecha_cambio timestamp(6) not null,
        id_historial bigint generated by default as identity,
        id_usuario_cambio bigint not null,
        id_venta bigint not null,
        estado_anterior varchar(30),
        estado_nuevo varchar(30) not null,
        primary key (id_historial)
    );

    alter table if exists catalogo.paquete 
       add constraint FK5s736ain1uy2r1jbpoppm6gsq 
       foreign key (id_destino) 
       references catalogo.destino;

    alter table if exists catalogo.paquete_aliado 
       add constraint FK3o24nhg3jq6upd0dcbcc5k2jo 
       foreign key (id_paquete) 
       references catalogo.paquete;

    alter table if exists catalogo.paquete_opcion 
       add constraint FK44nyv3qb59qideg51j3vqsk46 
       foreign key (id_paquete) 
       references catalogo.paquete;

    alter table if exists catalogo.paquete_vuelo 
       add constraint FKhi7cxsygri966ql9jqmh13bt6 
       foreign key (id_paquete) 
       references catalogo.paquete;

    alter table if exists catalogo.proveedor 
       add constraint FKs8ioxxnpelldd4ss2lfgupu7a 
       foreign key (id_destino) 
       references catalogo.destino;

    alter table if exists catalogo.tarifa 
       add constraint FKnge74fptresqjwvyhjhh4ada3 
       foreign key (id_destino) 
       references catalogo.destino;

    alter table if exists catalogo.tarifa 
       add constraint FK4f9ccwt66yml5fd4m7vgcq2a3 
       foreign key (id_proveedor) 
       references catalogo.proveedor;

    alter table if exists catalogo.tarifa 
       add constraint FK3gkc9jaqavugui89jad5dswu9 
       foreign key (id_servicio) 
       references catalogo.servicio;

    alter table if exists catalogo.tarifa_historial 
       add constraint FKhc53h269bgl7j186klb1sw4nj 
       foreign key (id_tarifa) 
       references catalogo.tarifa;

    alter table if exists catalogo.tarifa_historial 
       add constraint FKre55lhyyk8hntokbxtevi3863 
       foreign key (id_usuario_cambio) 
       references seguridad.usuario;

    alter table if exists seguridad.historial_password 
       add constraint FKjg3k4yrvqg7pw6ugdqu6jjqwv 
       foreign key (id_usuario) 
       references seguridad.usuario;

    alter table if exists seguridad.password_reset_token 
       add constraint FKno4ngi2ecktio49ytrq5d2cxh 
       foreign key (id_usuario) 
       references seguridad.usuario;

    alter table if exists seguridad.rol_permiso 
       add constraint FKsxc3d8lmtj7em6n8j0wl4jwco 
       foreign key (id_rol) 
       references seguridad.rol;

    alter table if exists seguridad.usuario_rol 
       add constraint FKkxcv7htfnm9x1wkofnud0ewql 
       foreign key (id_rol) 
       references seguridad.rol;

    alter table if exists seguridad.usuario_rol 
       add constraint FK3ftpt75ebughsiy5g03b11akt 
       foreign key (id_usuario) 
       references seguridad.usuario;

    alter table if exists ventas.cotizacion 
       add constraint FKw75lbg0fdtgkyckx3jucme0h 
       foreign key (id_agencia) 
       references ventas.agencia;

    alter table if exists ventas.cotizacion 
       add constraint FKbd2b8tnowhxujrrhdesmn9732 
       foreign key (id_asesor) 
       references seguridad.usuario;

    alter table if exists ventas.cotizacion_detalle 
       add constraint FKgh9i74gdpkvai7t9uyq2c73v8 
       foreign key (id_cotizacion) 
       references ventas.cotizacion;

    alter table if exists ventas.cotizacion_detalle 
       add constraint FK147ed5jjcr1qlpg2fkb7shscv 
       foreign key (id_tarifa) 
       references catalogo.tarifa;

    alter table if exists ventas.cotizacion_historial_estado 
       add constraint FKfgulnvofsjyshrtg80mwmv158 
       foreign key (id_cotizacion) 
       references ventas.cotizacion;

    alter table if exists ventas.cotizacion_historial_estado 
       add constraint FKfqeo4bnincndb6dus0jlot0ws 
       foreign key (id_usuario_cambio) 
       references seguridad.usuario;

    alter table if exists ventas.interaccion_agencia 
       add constraint FKfjp6hnqkyhfxkq4mku7lydbyy 
       foreign key (id_agencia) 
       references ventas.agencia;

    alter table if exists ventas.interaccion_agencia 
       add constraint FKrbdn16uk3nnp4b1kepfs4p0yx 
       foreign key (id_usuario_registro) 
       references seguridad.usuario;

    alter table if exists ventas.venta 
       add constraint FKfffk9nsfatmlettoyablib0c6 
       foreign key (id_agencia) 
       references ventas.agencia;

    alter table if exists ventas.venta 
       add constraint FKrpki5motc0ftufmsd3kvv0qbb 
       foreign key (id_cotizacion) 
       references ventas.cotizacion;

    alter table if exists ventas.venta 
       add constraint FKegbkm8sdgiwbp5bshs8lxgifc 
       foreign key (id_producto) 
       references catalogo.paquete;

    alter table if exists ventas.venta 
       add constraint FKnbhrv72fnoberatj674r74nxi 
       foreign key (id_tarifa) 
       references catalogo.tarifa;

    alter table if exists ventas.venta 
       add constraint FKce8xlrhv37t04q1uiem9ohycb 
       foreign key (id_usuario_registro) 
       references seguridad.usuario;

    alter table if exists ventas.venta_historial_estado 
       add constraint FK1yukf1hqsijwe2k2pny31g035 
       foreign key (id_usuario_cambio) 
       references seguridad.usuario;

    alter table if exists ventas.venta_historial_estado 
       add constraint FK284rpvp22bjmm7rgtjk3s1uiv 
       foreign key (id_venta) 
       references ventas.venta;
