-- ============================================================================
-- Nuevo Horizonte - Script de base de datos (PostgreSQL / pgAdmin)
-- Ejecutar con la base de datos "nuevo_horizonte" seleccionada.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABLA: usuario
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario (
    id_usuario      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)  NOT NULL UNIQUE,
    password_hash   VARCHAR(100) NOT NULL,
    email           VARCHAR(100) NOT NULL UNIQUE,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------------------------
-- TABLA: rol
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rol (
    id_rol      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(60) NOT NULL UNIQUE,
    descripcion VARCHAR(200)
);

-- ----------------------------------------------------------------------------
-- TABLA: usuario_rol  (relación usuario <-> rol)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario_rol (
    id_usuario_rol   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       BIGINT      NOT NULL,
    id_rol           BIGINT      NOT NULL,
    fecha_asignacion TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_rol_rol FOREIGN KEY (id_rol)
        REFERENCES rol (id_rol) ON DELETE CASCADE,
    CONSTRAINT uq_usuario_rol UNIQUE (id_usuario, id_rol)
);

-- ----------------------------------------------------------------------------
-- TABLA: rol_permiso  (permisos por módulo asociados a un rol)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rol_permiso (
    id_permiso    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol        BIGINT      NOT NULL,
    modulo        VARCHAR(60) NOT NULL,
    puede_leer    BOOLEAN     NOT NULL DEFAULT TRUE,
    puede_escribir BOOLEAN    NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_rol_permiso_rol FOREIGN KEY (id_rol)
        REFERENCES rol (id_rol) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- Índices auxiliares
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_usuario_rol_usuario ON usuario_rol (id_usuario);
CREATE INDEX IF NOT EXISTS idx_usuario_rol_rol     ON usuario_rol (id_rol);
CREATE INDEX IF NOT EXISTS idx_rol_permiso_rol     ON rol_permiso (id_rol);

-- ----------------------------------------------------------------------------
-- Seed: roles del sistema
-- ----------------------------------------------------------------------------
INSERT INTO rol (nombre, descripcion) VALUES
    ('Area de Producto', 'Gestion del inventario y catalogo de productos'),
    ('Area de Ventas',   'Gestion de clientes, pedidos y facturacion'),
    ('Gerencia',         'Reportes, indicadores y supervision general'),
    ('Administración',   'Acceso total a la administracion del sistema')
ON CONFLICT (nombre) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Nota: el usuario administrador (admin / admin123) se crea automáticamente
-- al arrancar la aplicación (Config/DataInitializer), con contraseña encriptada
-- con BCrypt. Si desea crearlo manualmente, inserte un hash BCrypt de la
-- contraseña en password_hash y asocie el rol 'Administración'.
-- ----------------------------------------------------------------------------